[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/codegangsta/cli"

[[constraint]]
  name = "github.com/golang/protobuf"
  # version = "~1.2.0"
  branch = "master"   # Using master for now because no tagged version of this repo supports the current version of the protoc tool

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.6.3"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
