---
- name: Sudo-level VM Prep
  hosts: all
  become: yes
  become_user: root
  vars:
    todd_dir: /home/vagrant/go/src/github.com/Mierdin/todd
    gover: 1.6.2  #Change this variable to update to a new version of Go
    gosha256: e40c36ae71756198478624ed1bb4ce17597b3c19d243f3f0899bb5740d56212a
  tasks:

  - name: Set up docker repo
    apt_repository:
      repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
      state=present

  - name: Install APT dependencies
    apt: pkg={{ item }} state=latest update_cache=yes force=yes  # Currently forcing because of a certificate error for docker-engine
    with_items:
    - git
    - docker-engine

  - name: Add vagrant user to docker group
    user: name=vagrant groups="docker" append=yes

  - name: Ensure docker service is restarted
    service: name=docker state=restarted

  - name: Download Go tarball
    get_url:
      url="https://storage.googleapis.com/golang/go{{ gover }}.linux-amd64.tar.gz"
      checksum="sha256:{{ gosha256 }}"
      validate_certs=no
      dest=/tmp/go{{ gover }}.linux-amd64.tar.gz
      mode=0770

  - name: Unzip Go tarball
    unarchive:
      src=/tmp/go{{ gover }}.linux-amd64.tar.gz
      dest=/usr/local
      copy=no

  - name: Config Files
    file:
      src={{ todd_dir }}/etc
      dest=/etc/todd
      state=link

  - name: Create opt dir
    file:
      path=/opt/todd
      state=directory
      owner=vagrant
      group=vagrant
      mode=0755

  - name: GOPATH Owner
    shell: chown vagrant:vagrant $(find /home/vagrant/go | grep -v todd) warn=no

- name: Prepping for ToDD
  hosts: all
  vars:
    todd_dir: /home/vagrant/go/src/github.com/Mierdin/todd
  tasks:

  - name: Set GOPATH for Vagrant user profile
    lineinfile: 
      dest=/home/vagrant/.profile
      state=present
      regexp='^export GOPATH'
      line='export GOPATH=/home/vagrant/go'

  - name: Set PATH for Vagrant user profile
    lineinfile: 
      dest=/home/vagrant/.profile
      state=present
      regexp='^export PATH'
      line='export PATH=$PATH:/home/vagrant/go/bin:/usr/local/go/bin:{{ todd_dir }}/scripts'

  - name: cd to todd_dir when logging in
    lineinfile: 
      dest=/home/vagrant/.profile
      state=present
      regexp='^cd '
      line='cd {{ todd_dir }}'

  # - name: Start etcd and rabbitmq containers
  #   shell: cd {{ todd_dir }}/scripts && ./start-containers.sh
  #   sudo: yes

  - name: Print follow-up instructions
    debug: msg="READY TO INSTALL TODD. PLEASE RUN 'sudo make install' IN {{ todd_dir }}"
